function createReport()
    
    publish('evaluationT1.m', struct(...
            'figureSnapMethod', 'print',...
            'outputDir', './html/',...
            'showCode', false,...
            'createThumbnail', false )...
           );
    
%{
    publish('evaluationT2.m', struct(...
            'figureSnapMethod', 'print',...
            'outputDir', './html/',...
            'showCode', false,...
            'createThumbnail', false )...
           );
%}
           
end
